version: '3.8'  # Standardowa, stabilna wersja specyfikacji Dockera

services:
  # --- INFRASTRUKTURA DANYCH ---

  # Główna baza danych dla Fintechu i Monitoringu
  postgres:
    image: postgres:15-alpine  # Alpine = bardzo lekki obraz Linuxa (bezpieczeństwo i szybkość)
    container_name: portfolio_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password  # W produkcji używalibyśmy pliku .env!
      POSTGRES_DB: portfolio_main
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Trwałość danych (Persistent Storage)
    networks:
      - portfolio_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d portfolio_main"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Cache dla B2B oraz Broker wiadomości dla Celery
  redis:
    image: redis:7-alpine
    container_name: portfolio_redis
    networks:
      - portfolio_network

  # --- API GATEWAY ---
  
  service-b2b:
    build: ./service-b2b-data
    container_name: b2b_service
    ports:
      - "8001:8001"
    depends_on:
      - redis
    networks:
      - portfolio_network

  # --- FRONTEND (React + Vite) ---
  frontend:
    build: ./frontend-landing
    container_name: portfolio_frontend
    volumes:
      - ./frontend-landing:/app
      - /app/node_modules # Nie nadpisujemy node_modules z kontenera lokalnymi
    environment:
      - VITE_API_URL=/api
    networks:
      - portfolio_network

  nginx:
    image: nginx:1.25-alpine
    container_name: portfolio_gateway
    ports:
      - "80:80"  # Mapujemy port 80 Twojego komputera na port 80 kontenera
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mapujemy nasz plik konfiguracyjny
    depends_on:
      - postgres
      - redis
    networks:
      - portfolio_network

# Definicja sieci - wszystkie kontenery w tej sieci widzą się po nazwach (np. "postgres")
networks:
  portfolio_network:
    driver: bridge

# Definicja wolumenów - to są "wirtualne dyski", które przeżyją usunięcie kontenera
volumes:
  postgres_data:
